config/routes.rb
Book2::Application.routes.draw do
  resources :books
  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :amazon_url %><br />
    <%= f.text_field :amazon_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= stylesheet_link_tag "books" %>  

<%= link_to 'Add a book', new_book_path %>

<ul class='unstyled'>
<% @books.each do |book| %>
    <li>      
    <article>
        <header>
            <strong>
                <%= book.author %>,
            </strong>     
            <%= book.title %>
            

        </header>
        <div>
            <%= book.description %>
            <%= book.rating %>
            <%= image_tag(book.image_url, :size => '20%') %>
            <%= link_to(book.amazon_url, :text => 'Buy this book on Amazon.com') %>     
        </div>
    </article>
    </li>
<% end %>
</ul>
<br />

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @book.rating %>
</p>

<p>
  <b>Image url:</b>
  <%= @book.image_url %>
</p>

<p>
  <b>Amazon url:</b>
  <%= @book.amazon_url %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "bootstrap" %>  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<header>
			<h1>Book</h1>
			<nav>
				Placeholder for navigation
			</nav>	
		</header>
		<%= yield %>
	</div>
</body>
</html>